title: My first blog
author: Samarth Parnami
email: samarthparnami@gmail.com
description: This is my first blog where we talk about the github journey I took while working on a project for my resume.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
theme : minima
show_excerpts: true # set to false to remove excerpts on the homepage

